### ISSUE TITLE
Unable to Download E.Coli Sequence Files

### ISSUE THREAD

**Issue by souravsingh** [peterjc/biopython_workshop#1]
I tried to use the shell script to download the Sequence Files.But the sequence files failed to download.

**Comment by peterjc** [comment]
Probably the NCBI FTP site changed again... I'll have to look at that, thanks.

Peter

**Comment by peterjc** [comment]
Does that work for you now?

**Comment by souravsingh** [comment]
@peterjc It is working really nicely. Thanks a lot!!

**Comment by peterjc** [comment]
Great - thanks for getting in touch & double checking the fix for me.
